package app.truearena.api.slay;

import app.truearena.engine.slay.SlayRules.*;

import com.fasterxml.jackson.databind.ObjectMapper;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.util.*;

@Component
public class SlayCatalog {
    public record Client(String id, String name, String brief, String themeId) {}

    public record Avatar(String body, String assetUrl, String rigVersion) {}

    /** One delivered art file: its content-hashed name under {@code base}, and whether the app bundles it. */
    public record AssetFile(String name, String sha256, long bytes, boolean bundled) {}

    /** Generated by the renderer build (publish-assets.mjs); maps catalogue paths to delivered files. */
    public record Assets(String base, Map<String, AssetFile> files) {}

    public record Manifest(
            int version,
            boolean developmentAssets,
            List<Avatar> avatars,
            List<Item> items,
            List<Theme> themes,
            List<String> poses,
            List<String> backgrounds,
            List<String> skinTones,
            List<String> facePresets,
            List<Client> clients,
            Assets assets) {}

    private final Manifest manifest;

    public SlayCatalog(
            ObjectMapper mapper, @Value("${truearena.slay.asset-base:}") String assetBase)
            throws Exception {
        Manifest catalog;
        try (var in = new ClassPathResource("slay/catalog.json").getInputStream()) {
            catalog = mapper.readValue(in, Manifest.class);
        }
        Assets assets = null;
        var delivered = new ClassPathResource("slay/asset-manifest.json");
        if (delivered.exists()) {
            try (var in = delivered.getInputStream()) {
                assets = mapper.readValue(in, Assets.class);
            }
            if (!assetBase.isBlank()) {
                assets =
                        new Assets(
                                assetBase.endsWith("/") ? assetBase : assetBase + "/",
                                assets.files());
            }
        }
        manifest =
                new Manifest(
                        catalog.version(),
                        catalog.developmentAssets(),
                        catalog.avatars(),
                        catalog.items(),
                        catalog.themes(),
                        catalog.poses(),
                        catalog.backgrounds(),
                        catalog.skinTones(),
                        catalog.facePresets(),
                        catalog.clients(),
                        assets);
    }

    public Manifest manifest() {
        return manifest;
    }

    public Map<String, Item> items() {
        Map<String, Item> items = new LinkedHashMap<>();
        manifest.items().forEach(i -> items.put(i.id(), i));
        return items;
    }

    public Theme theme(String id) {
        return manifest.themes().stream()
                .filter(t -> t.id().equals(id))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Unknown theme"));
    }
}
